name: Sync upstream and build image

on:
  schedule:
    - cron: "23 4 * * 1"   # Mondays 04:23 UTC
  workflow_dispatch: {}

permissions:
  contents: write     # to push to main
  packages: write     # to push to GHCR

env:
  UPSTREAM_REPO: JustTemmie/steam-presence
  BRANCH: main
  IMAGE_NAME: steam-presence

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git || true
          git fetch upstream ${{ env.BRANCH }}

      - name: Check behind/ahead and merge if needed
        id: check
        run: |
          git checkout $BRANCH
          read BEHIND AHEAD < <(git rev-list --left-right --count upstream/$BRANCH...$BRANCH | awk '{print $1" "$2}')
          echo "Behind: $BEHIND  Ahead: $AHEAD"
          if [ "$BEHIND" -gt 0 ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git merge --no-edit upstream/$BRANCH
            git push origin $BRANCH
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to sync."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: sync
    if: needs.sync.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout updated main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

